### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cyberfly79** [TomerFi/home-assistant-custom-ui#2]
Hi,

I wanted to use this, but unfortunately there are more errors in the log and the text is only changed in the popup. (HA 0.86.4 lovelace ui)

ERROR (MainThread) [frontend.js.latest.201901211] https://xxxxxxxx.duckdns.org/frontend_latest/app-3b4bb4ed.js:89:1213 TypeError: localize is not a function. (In 'localize(`ui.components.relative_time.duration.${langKey[i]}`,"count",delta)', 'localize' is undefined)

ERROR (MainThread) [frontend.js.latest.201901211] https://xxxxxxxxxxxx.duckdns.org/frontend_latest/app-3b4bb4ed.js:89:305
Uncaught TypeError: localize is not a function

thnx

**Comment by TomerFi** [comment]
Yeah this solution was a "pre-lovelace" solution, I highly doubt it'll work today.
I believe there are better ways to accomplish script naming issue.
